using System;
using System.Linq;
using System.Threading.Tasks;

namespace HuajiTech.Mirai.Events
{
    /// <summary>
    /// 定义事件源
    /// </summary>
    public class EventSource
    {
        /// <summary>
        /// 异步调用事件
        /// </summary>
        /// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
        /// <param name="handlers">Event handlers.</param>
        /// <param name="e">An object that contains the event data.</param>
        internal async Task InvokeAsync<TEventArgs>(AsyncEventHandler<TEventArgs> handlers, Session session, TEventArgs e)
            where TEventArgs : EventArgs
        {
            if (handlers != null)
            {
                await handlers.Invoke(session, e);
            }
        }

        /// <summary>
        /// 移除所有 Handlers
        /// </summary>
        internal void RemoveAllHandlers()
        {
            foreach (var eventField in GetType().GetEvents().Select(x => GetType().GetField(x.Name)!))
            {
                eventField?.SetValue(this, null);
            }
        }

        /// <summary>
        /// 创建 <see cref="EventSource"/> 实例
        /// </summary>
        public EventSource()
        {
        }
    }
}