using System.Threading.Tasks;

namespace HuajiTech.Mirai.Events
{
    /// <summary>
    /// 定义事件源
    /// </summary>
    public class EventSource : SessionProcessor
    {
        /// <summary>
        /// 异步调用事件
        /// </summary>
        /// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
        /// <param name="handlers">Event handlers.</param>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">An object that contains the event data.</param>
        /// <returns></returns>
        internal async Task InvokeAsync<TEventArgs>(EventHandler<TEventArgs> handlers, TEventArgs e)
        {
            if (handlers != null)
            {
                await handlers.Invoke(Session, e);
            }
        }

        /// <summary>
        /// 创建 <see cref="EventSource"/> 实例
        /// </summary>
        /// <param name="session">指定 <see cref="EventSource"/> 实例所使用的会话</param>
        internal EventSource(Session session) : base(session)
        {
        }
    }
}